import{a as v,S as q,i as l}from"./assets/vendor-DjDxajEQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const S="https://pixabay.com/api",w="46511774-6d45b03e21a284b47c5b7e772",m=async(t,o)=>{const s={key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return v.get(S,{params:s})},M=()=>{page+=1};function p(t){const o=document.querySelector(".gallery"),s=t.map(({webformatURL:a,largeImageURL:e,tags:r,likes:i,views:g,comments:L,downloads:b})=>`
        <li><a href="${e}" class="gallery-item" data-lightbox="image">
            <div class="image-container"><img src="${a}" alt="${r}" loading="lazy" /></div>
            <div class="card-description">
                <p class="info"><span>Likes</span> ${i}</p>
                <p class="info"><span>Views</span> ${g}</p>
                <p class="info"><span>Comments</span> ${L}</p>
                <p class="info"><span>Downloads</span> ${b}</p>
            </div>
        </a></li>
    `).join("");o.insertAdjacentHTML("beforeend",`<ul class="gallery-list">${s}</ul>`)}const y=()=>{document.querySelector(".load-more").classList.remove("hidden")},u=()=>{document.querySelector(".load-more").classList.add("hidden")},f=()=>{const t=document.querySelector(".gallery");t.innerHTML=""},h=new q(".gallery a",{overlayOpacity:.8,captions:!0,captionDelay:250,captionPosition:"bottom",captionType:"attr",captionsData:"alt"});let n=1,c="";const B=document.querySelector(".search-form"),P=document.querySelector(".load-more"),d=document.querySelector("#loader"),E=async t=>{t.preventDefault();const o=t.target,s=o.elements.query.value.trim();if(s)c===s?M():(c=s,n=1);else return;o.reset(),d.classList.remove("hidden");try{const{data:a}=await m(c,n);if(a.total===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");p(a.hits),a.totalHits<=15*n?(u(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):y(),h.refresh()}catch(a){l.error({title:"Error",message:a.message}),f()}d.classList.add("hidden")};B.addEventListener("submit",E);const $=async()=>{n+=1,u(),d.classList.remove("hidden");try{const{data:t}=await m(c,n);p(t.hits),t.totalHits<=15*n?(u(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):y();const s=document.querySelector(".gallery-list a").getBoundingClientRect().height;window.scrollBy({top:s*2,left:0,behavior:"smooth"}),h.refresh()}catch(t){l.error({title:"Error",message:t.message}),f()}d.classList.add("hidden")};P.addEventListener("click",$);
//# sourceMappingURL=index.js.map
