import{a as m,S as b,i as l}from"./assets/vendor-DjDxajEQ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="46511774-6d45b03e21a284b47c5b7e772";m.defaults.baseURL="https://pixabay.com/api/";const p=(e,r)=>m.get("",{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}}),y=document.querySelector(".gallery"),f=({webformatURL:e,largeImageURL:r,tags:o,likes:a,views:t,comments:s,downloads:i})=>`
<li>
  <a href="${r}">
    <div class="image-container">
      <img class="image-preview" src="${e}" alt="${o}" />
    </div>
    <div class="card-description">
      <span class="attribute"><span>Likes</span> ${a}</span>
      <span class="attribute"><span>Views</span> ${t}</span>
      <span class="attribute"><span>Comments</span> ${s}</span>
      <span class="attribute"><span>Downloads</span> ${i}</span>
    </div>
  </a>
</li>
  `,q=e=>{const r=e.map(f).join("");y.innerHTML=`<ul class="gallery-list">${r}</ul>`},w=e=>{const r=e.map(f).join("");document.querySelector(".gallery-list").insertAdjacentHTML("beforeend",r)},h=()=>{document.querySelector(".load-more").classList.remove("hidden")},d=()=>{document.querySelector(".load-more").classList.add("hidden")},g=()=>{y.innerHTML=""},L=new b(".gallery a",{overlayOpacity:.8,captions:!0,captionDelay:250,captionPosition:"bottom",captionType:"attr",captionsData:"alt"});let n=1,c="";const M=document.querySelector(".search-form"),S=document.querySelector(".load-more"),u=document.querySelector("#loader"),B=async e=>{e.preventDefault();const r=e.target,o=r.elements.query.value.trim();if(o)c===o?page+=1:(c=o,n=1);else return;r.reset(),u.classList.remove("hidden");try{const{data:a}=await p(c,n);if(a.total===0)throw d(),new Error("Sorry, there are no images matching your search query. Please try again!");q(a.hits),a.totalHits<=15*n?(d(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):h(),L.refresh()}catch(a){l.error({title:"Error",message:a.message}),g()}u.classList.add("hidden")};M.addEventListener("submit",B);const P=async()=>{n+=1,d(),u.classList.remove("hidden");try{const{data:e}=await p(c,n);w(e.hits),e.totalHits<=15*n?(d(),l.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):h();const o=document.querySelector(".gallery-list a").getBoundingClientRect().height;window.scrollBy({top:o*2,left:0,behavior:"smooth"}),L.refresh()}catch(e){l.error({title:"Error",message:e.message}),g()}u.classList.add("hidden")};S.addEventListener("click",P);
//# sourceMappingURL=index.js.map
